
POST http://localhost:5000/api/wilderwithskills
Content-Type: application/json

{"wilderName": "jane doe", "skillName": "PHP"}

###
POST http://localhost:5000/api/wilder
Content-Type: application/json

{"name": "jane doe", "city":"Lyon", "email":"jane@email.fr"}

###

GET http://localhost:5000/api/wilder

###

PUT http://localhost:5000/api/wilder/1
Content-Type: application/json

{"name":"jane doe"}

###

DELETE http://localhost:5000/api/wilder/2